//= Components
import LoginForm from "@/components/Authentication/Login";
//= Types
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BlackIN | Login",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return (
    <LoginForm />
  );
}
