import { cookies } from "next/headers";
import localFont from "next/font/local";
//= Components
import { Toaster } from 'sonner';
import Navbar from "@/components/Shared/Navbar";
//= Types
import type { Metadata } from "next";
//= Styles
import "@/styles/globals.scss";

const UrbanistFont = localFont({
  src: "./fonts/Urbanist.ttf",
  variable: "--font-family",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Login Page Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const token = cookies().get('token');

  return (
    <html lang="en">
      <body className={UrbanistFont.variable}>
        <Navbar isLogggedIn={token?.value ? true : false} />
        {children}
        <Toaster
          position="bottom-right"
          toastOptions={{ duration: 5000 }}
        />
      </body>
    </html>
  );
}
