//= Components
import WelcomeScreen from "@/components/Dashboard/Welcome";
//= Types
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "BlackIN Dashboard",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <WelcomeScreen />
  );
}
